### ISSUE TITLE
[BUG/FEATURE] Navbar Heights

### ISSUE THREAD

**Issue by sjclark** [FrDH/mmenu-js#1005]
In the old version it was possible to set navbar heights within the config itself; now it seems like these are ignored.
```
"navbars": [{
          "position": "top",
          "content": [
            "<div style='padding: 20px;'><img style='max-width: 100%; max-height: 100%' src='/assets/theme-assets/img.img'></div>"
          ],
          "height": 2
        }
      ]
```

This seems to have been depreciated in favour of declaring the styling in css with a single `$mm_navbarSize` or `--mm-navbar-size` resulting in the inability to style each individual navbar.

Setting say a **logo header** and having the menu headings on results in both being a large size.
![Screen Shot 2019-05-15 at 4 02 32 PM](https://user-images.githubusercontent.com/4531017/57747740-f4266700-772a-11e9-9a4f-9782202ef7ef.png)

What is the suggested pathway to styling different navbars differently - is it possible to declare a class for each navbar?

EDIT: Actually it looks like having a class on each navbar element wouldn't work in any case; as the the height the menu is placed from the top is dictated by a navbar variable too...
```
.mm-menu_navbar_top-1 .mm-panels {
    top: 44px;
    top: calc(var(--mm-navbar-size) * 1);
```
So even if you override the height of the specific navbar element it protrudes into the menu.

As a further note; the "Prepend a fixed header to the menu." no longer works in the website documentation.
https://mmenujs.com/examples.html

**Comment by FrDH** [comment]
Hi,

In the new version you can indeed use the `--mm-navbar-size` css variable to set the height for each navbar. You can also simply override the `height` css value. I realize it is a bit hard to target a specific navbar, but you could try something like this:
````css
.mm-navbars_top > .mm-navbar:first-child {
   --mm-navbar-size: 80px;
}
````

Where did you find that CSS? It appears to be from an older version.

The example seems to be working, it's just not very clear the navbar is fixed because the listview isn't long enough to be scrolled. You can tell it is fixed because it doesn't scroll out to the left along with the panels.

Hope this helps.

**Comment by sjclark** [comment]
You're correct! Somehow I'd got jquery.mmenu from npm instead of mmenu-js. Have gone through an updated everything - seems to be working correctly now!

Thanks so much!

**Comment by sjclark** [comment]
Sorted!
