### ISSUE TITLE
Mmenu steals focus from inputs in form

### ISSUE THREAD

**Issue by brgrz** [FrDH/mmenu-js#1069]
Whenever the mmenu is enabled and immediately after it renders itself it steals the focus from input controls. I'm using the `autofocus `attribute on input or the following jQuery code to set focus but mmenu steals it in both cases:

```
	$(document).ready(function () {
		$('form :input:visible:enabled:first').focus();
	});

```

**Comment by FrDH** [comment]
This could be due to the `keyboardNavigation` add-on, it sets focus on the first focusable element when opening a panel. When the menu is created, it  "opens" the panel that should be opened.

If you have the keyboardNavigation add-on enabled, please try to disable it:
````js
cons menu = new Mmenu({
   keyboardNavigation: false
});
````

If that doesn't help, you could always wrap a `setTimeout` around your JS:
````js
$(document).ready(function () {
    setTimeout(function() {
        $('form :input:visible:enabled:first').focus();
    }, 100)
});
````

Hope this helps.
