### ISSUE TITLE
mmenu-js with Max Mega Menu Wordpress Plugin

### ISSUE THREAD

**Issue by AlexandraKaulfuss** [FrDH/mmenu-js#1075]
Hi,

I created a Mega Menu with the Max Mega Menu plugin in Wordpress and was trying to use mmenu-js for the mobile solution. Without the Max Mega Menu plugin everything works fine but when I activate the plugin the mmenu is populated but the panels are hidden instead of opened. Does anyone know why?

Best,
Alex

**Comment by FrDH** [comment]
Probably due to the CSS that is added by the mega-menu, is there an online example I could have a look at?

**Comment by SJNBham** [comment]
I ran into a similar issue. Check that you're not targeting the Max Mega Menu ID in the mmenu setup for the "Locate the menu" option. That setting should point to the primary nav of your site theme (e.g. #primary-nav). Here's an example:

![image](https://user-images.githubusercontent.com/11393597/69183868-a10de200-0ac8-11ea-82e7-38b34776dc88.png)

You may also want to add the following to the Max Mega Menu Themes Custom Styling tab to suppress the MMM mobile menu:

```
@include mobile {
    #{$wrap} {
        display: none;
    }
}
```
Let me know if this works for you. I'm still trying to fine-tune Max Mega Menu, mmenu.js, and my theme's primary nav.

**Comment by AlexandraKaulfuss** [comment]
@SJNBham I had the same idea. I added the css id "primary-menu" to the html nav-Tag but unfortunately the menu creates a new line with "MENUMENU" and only exists of 1 layer (if you click the arrows on the right side it opens a blank space in the mmenu).

![mmenu bug](https://user-images.githubusercontent.com/48352360/69235399-9ff4b780-0b91-11ea-918d-8f18d2992991.PNG)


I tried to create a second hidden menu with the same menu items and it worked ok, but I only had max 2 layers with it. If I disable the Max Mega Menu Plugin mmenu has no problem at all and works just fine with 3 or 4 layers or more.

**Comment by SJNBham** [comment]
I've been doing some further testing and found two configuration points you may want to work with.

In MMM, there's an option Active Menu Instances. Try adjusting this number. I eventually settled on 2 instead of the default of 0. I think this is because my site theme provides multiple primary menu options.

In mmunu.js, you may want to try using more specific selectors. For example, for the menu I'm using "#mobile-header #mobile-menu" instead of just "#mobile-menu" now. It seems to be working better that way even though the GUI warns it can't find that selector on the page. 

![image](https://user-images.githubusercontent.com/11393597/69361316-18ff1800-0c41-11ea-831c-4e6ae32af332.png)
