### ISSUE TITLE
Request: Add support for accordion style submenus

### ISSUE THREAD

**Issue by arkid** [FrDH/mmenu-js#1234]
From what I understand this isn't possible out of the box with mmenu or any plugin for it.   What I need is an easy way to format the submenus so that they are clickable and collapse/expand, as is clear from this screenshot:

![image](https://user-images.githubusercontent.com/3810108/120843795-867d4b80-c53c-11eb-8683-b6a84f63058f.png)

If I'm wrong about mmenu's ability to support this please just let me know ;)

**Comment by valentynpopov** [comment]
If you use CSS class "Vertical", you can achieve something a bit similar

**Comment by arkid** [comment]
Sorry this is something rreally basic but I've checked [the documentation](https://mmenujs.com/docs/core/configuration.html#h1) and yet the config seems to be ignored.   Am I not defining it correctly ?

```
jQuery("#menuNav").mmenu({
		// options
		},{
		// configuration
		classNames: {
            vertical: "Vertical"
        }
});
```

**Comment by valentynpopov** [comment]
You need to add "Vertical" CSS class to the `<ul>` elements which you want to be accordion-like. It could be either all of the `<ul>` elements, or you may have a mixture of sliding and accordion (vertical) sub menus.

Changing mmenu configuration (like you did) isn't really necessary unless you prefer to use a different CSS class, like 'accordion' or 'vertical-menu' instead of the default 'Vertical' CSS class.

**Comment by arkid** [comment]
Ahhhh with you, yes fantastic!   Ok I'm on my way now, I will just add some extra custom css to format how I want but yes it basically works already.    Thanks so much @valentynpopov  ! :)
