### ISSUE TITLE
New WP plugin is bugged

### ISSUE THREAD

**Issue by gleenk** [FrDH/mmenu-js#1289]
2 big-bugs:

1. Can't choose menu side, it's alway on the left
2.  It create conflicts with other page elements forcing position-relative on body.

**Comment by alessandro-newzoo** [comment]
@FrDH has this fixed actually been released though? The latest version available on your website (3.1.0) released in May but you marked this as completed in June, and the issue is indeed still there. No matter what option I choose, it's always coming from the left.
I really wanna buy it but I need this to work first :/

Thanks!

**Comment by gleenk** [comment]
Same here. I had to remove the plugin on all production sites due to this bug, and made a custom one...
