### ISSUE TITLE
Menu not working on IOS13

### ISSUE THREAD

**Issue by minh-pn** [FrDH/mmenu-js#1298]
I tested demo link: https://mmenujs.com/ on ios13.
But the menu not working. (Still good on ios15 or Android).
Maybe newest version still has issue.
Someone can help me?
Thank you.

**Comment by GilbertLC** [comment]
#1301 
mmenu.css - :where(.mm-slideout) is unsupported by Safari 13.1 or lower - see: https://caniuse.com/mdn-css_selectors_where

**Comment by juergen1964** [comment]
Hi there,
i can confirm the behavior on iPhone 5 (safari version 12.5). Unfortunatly the Safari version 12.5 for iPhone 5 is the latest version available for my iPhone 5, not sure if there will be a update in the future, probably not.

Anyway, is there a solution or a workaround to make mmenu working on iPhone 5? GilbertLC told the :where(.mm-slideout) caused the problem, because it is not suported by safari 13.1 or lower. So if it is a css issue, it should be possible to fix it, right? I never used :where selector and i am not really sure what it is used for.

I found the :where in the mmenu.offcanvas.scss file:

//  All sliding out nodes
:where(.mm-slideout) {
    position: relative;
    z-index: 1;
    width: 100%;
    transition-duration: v.$transDr;
    transition-timing-function: v.$transFn;
    transition-property: width, transform;
}

Not sure if the  ":where" is used somewhere else and what "all sliding out nodes" are. I tryed just to use
.mm-slideout() without the :where, but like expected this will not work.

Would be nice if somebody got a hint or a solution to share.
Thx a lot and have a nice day

**Comment by minh-pn** [comment]
Hi all, I found the problem on CSS. I think it's not cause :where.
The problem is the attribute: **clamp(var(--mm-min-size),var(--mm-size),var(--mm-max-size)**.
I tried change to width: 100vw, or height: 100vw. And they work fine.
My website: https://financia-business-school.com/
------------------
Hope help someone.

**Comment by juergen1964** [comment]
Hi minh-pn,
i can confirm that your menu is working on my iPhone 5, congratulation!

My menu will not work with your solution. I am sure my problem is different. Anyway i can see yours is working, so i am motivated to make mine working too - there must be a way to do so. I will give em a try and will report.

Btw:: Are You useing the version 9.1?

Thx a lot - goot job!

**Comment by minh-pn** [comment]
Hi @juergen1964,
Thanks for your confirming.
I'm using v9.0.
Try your best.
